# Example GitLab CI/CD Pipeline
# This file is for reference only - copy to .gitlab-ci.yml if needed

variables:
  AWS_REGION: us-east-1
  PYTHON_VERSION: "3.11"
  NODE_VERSION: "18"
  DOCKER_DRIVER: overlay2

stages:
  - test
  - build
  - deploy

# Backend Testing
test:backend:
  stage: test
  image: python:${PYTHON_VERSION}
  before_script:
    - cd backend
    - pip install -r requirements.txt
  script:
    - pytest --cov=app --cov-report=xml --cov-report=term
  coverage: '/TOTAL.*\s+(\d+%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml

# Frontend Testing
test:frontend:
  stage: test
  image: node:${NODE_VERSION}
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run lint
    - npm run build
  cache:
    paths:
      - frontend/node_modules/
  artifacts:
    paths:
      - frontend/dist/
    expire_in: 1 day

# Build Backend Docker Image
build:backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
    - develop
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - cd backend
    - docker build -t $ECR_REGISTRY/s3-storage-backend:$CI_COMMIT_SHA .
    - docker tag $ECR_REGISTRY/s3-storage-backend:$CI_COMMIT_SHA $ECR_REGISTRY/s3-storage-backend:latest
    - docker push $ECR_REGISTRY/s3-storage-backend:$CI_COMMIT_SHA
    - docker push $ECR_REGISTRY/s3-storage-backend:latest

# Build Frontend Docker Image
build:frontend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  only:
    - main
    - develop
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
  script:
    - cd frontend
    - docker build -t $ECR_REGISTRY/s3-storage-frontend:$CI_COMMIT_SHA .
    - docker tag $ECR_REGISTRY/s3-storage-frontend:$CI_COMMIT_SHA $ECR_REGISTRY/s3-storage-frontend:latest
    - docker push $ECR_REGISTRY/s3-storage-frontend:$CI_COMMIT_SHA
    - docker push $ECR_REGISTRY/s3-storage-frontend:latest

# Deploy to Staging
deploy:staging:
  stage: deploy
  image: amazon/aws-cli
  environment:
    name: staging
    url: https://staging.yourdomain.com
  only:
    - develop
  script:
    - aws ecs update-service --cluster s3-storage-staging --service backend --force-new-deployment --region $AWS_REGION
    - aws ecs update-service --cluster s3-storage-staging --service frontend --force-new-deployment --region $AWS_REGION
    - echo "Deployed to staging environment"

# Deploy to Production
deploy:production:
  stage: deploy
  image: amazon/aws-cli
  environment:
    name: production
    url: https://app.yourdomain.com
  only:
    - main
  when: manual
  script:
    - aws ecs update-service --cluster s3-storage-prod --service backend --force-new-deployment --region $AWS_REGION
    - aws ecs update-service --cluster s3-storage-prod --service frontend --force-new-deployment --region $AWS_REGION
    - echo "Deployed to production environment"
